### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by patriciachrysy** [patriciachrysy/apple-product-page-clone#2]
waiting for your feedbacks

**Comment by nyatindopatrick** [comment]
Clean Code and nice gradient. I noticed this behaviour when reducing browser width:
- The navigation bar loses shape in small screen. I thought you should try setting an absolute width for the navigation to prevent this behaviour.
![Screen Shot 2020-01-31 at 10 14 48](https://user-images.githubusercontent.com/48393059/73519830-212ebd00-4413-11ea-8717-289bd73f3ba4.png)

Good work though.

**Comment by Kyle-Law** [comment]
Great job Patricia! Your clone page is awesome and achieved what's required by the project. Below are some optional or minor suggestions that I could see:

1) The form part breaks into 2 rows for smaller sizes. Whenever this happens, try `display: flex;` and `align-items: center;` on the parent container. (Not required for this project)
2) The navbar items are not vertically centered. Give `flexnac ul` `align-items: center;` will solve the issue.
3) Besides giving `footer-bottom` a padding-left and `footer-top` a `text-align: center` You could remove both of them to align footer-bottom and footer top at the same starting point.
4) Besides of giving `flex: 1;` to both items inside footer-top, you could also achieve that by giving `justify-content: space-between` to the footer-top to align its children at left and right part automatically. (You could only use that if you have 2 children)
5) Give `.nav-text:hover` a `cursor: pointer;` to make the cursor become pointer upon hover to the `li` box. 

Nevertheless, it's a great clone! 👍

**Comment by dili021** [comment]
Very nice and clean. The only difference I see compared to the original is that your h1 and the p bellow it are not links. The rest is spot on!

**Comment by Kyle-Law** [comment]
Above @nyatindopatrick comment could be fixed by giving the form `display: flex;` and `align-items: center`.

**Comment by patriciachrysy** [comment]
Thank you guys for your suggestion, I will try each of them.
